Fixed Rider support.
lunaryorn/jetbrains-search-provider pull request #10
Opened 2020-08-24 18:36 UTC by axelgenus

After all, it seems that adding Rider support was not so simple as I thought. Rider does not have a _recentProjects.xml_ file but has a _recentSolutions.xml_. Also, solutions are files, not directories. In order to fix it, I added 'recent_file' to ProductInfo tuple so that every product supplies the file name of its recent workspaces.

I also changed the way _find_projects.py_ behaves when it cannot find the recent file. I found out that if you've just installed a new IDE from Toolbox (in my case PyCharm) but never really opened any project, the IDE never creates _recentProjects.xml_. The script just returns an error and that's not really nice IMO. Now it just indexes whatever it can find.

2020-08-24 18:37 UTC, axelgenus commented
Sorry for the duplicated PR but I thought Jetbrains had a standard way to do things among IDE's...

2020-08-27 08:11 UTC, lunaryorn requested changes
Thanks, but this needs a few changes.

2020-08-27 08:11 UTC, lunaryorn commented on find-projects.py
> +    ProductInfo(key='rider', config_glob='Rider*', recents_file='recentSolutions.xml'),
As far as I can see only rider is different here, so I'd not like to clutter this tuple with `recents_file`.  Instead just check inside `find_latest_recent_projects_file` if `key == 'rider'` and use a different filename.

2020-08-27 08:11 UTC, lunaryorn commented on find-projects.py
> +        namefile = path.expanduser() / '.idea' / '.name'
I prefer ternary expressions instead of assignments in `if`s so please extract the first into `project_dir = path.parent if path.expanduser().is_file() else path`, and then `namefile = project_dir / '.idea' / …`.

2020-08-27 08:11 UTC, lunaryorn commented on find-projects.py
> -        if directory.expanduser().is_dir():
I don't think you can remove this check; the recents file can easily contain non-existing paths because Idea doesn't clean it up automatically.

2020-08-27 08:11 UTC, lunaryorn commented on find-projects.py
> +        if config_file and os.path.exists(config_file):
This check should 1) use the pathlib API instead of `os.path`, and 2) move into `find_latest_recent_projects_file` so that it returns `None` if the `config_file` doesn't exist.

2020-08-27 08:13 UTC, lunaryorn commented
I also noticed that your commit isn't linked to your account; if that's accidental you'll need to check the mail addresses associated w/ your Github account.

2020-08-27 14:14 UTC, axelgenus commented on find-projects.py
> +    ProductInfo(key='rider', config_glob='Rider*', recents_file='recentSolutions.xml'),
Done.

2020-08-27 14:15 UTC, axelgenus commented on find-projects.py
> +        namefile = path.expanduser() / '.idea' / '.name'
Done.

2020-08-27 14:15 UTC, axelgenus commented on find-projects.py
> -        if directory.expanduser().is_dir():
Since Rider solutions are files and not directories, I replaced the check with Path.exists().

2020-08-27 14:30 UTC, axelgenus commented on find-projects.py
> +        if config_file and os.path.exists(config_file):
Done.

2020-08-27 14:31 UTC, axelgenus commented
> I also noticed that your commit isn't linked to your account; if that's accidental you'll need to check the mail addresses associated w/ your Github account.

It is probably because I use SSH and I am using my work PC which uses another e-mail address for GIT.

2020-08-27 14:36 UTC, lunaryorn requested changes
It looks as if you changed the entire indentation of the script; can you please undo that?

2020-08-27 14:41 UTC, axelgenus commented
> It looks as if you changed the entire indentation of the script; can you please undo that?

Now it should be fixed.

2020-08-27 15:30 UTC, lunaryorn requested changes

2020-08-27 15:30 UTC, lunaryorn commented on find-projects.py
> +        ('recentSolutions.xml' if product.key == 'rider' else 'recentProjects.xml')
Can you extract this ternary expression into an extra variable, e.g `fileName`?  That'd be a tad easier to read imho.

2020-08-27 15:30 UTC, lunaryorn commented on find-projects.py
> +    if Path.exists(config_file):
This won't do… `Path.exists` isn't a static method and shouldn't be used as such.

2020-08-27 15:30 UTC, lunaryorn commented on find-projects.py
> +        if Path.exists(path.expanduser()):
As above, please don't use `Path.exists` like a static method.

2020-08-27 15:30 UTC, lunaryorn commented on find-projects.py
> +    if Path.exists(config_file):
Also, a ternary expression would be shorter, i.e. `return config_file if config_file.exists() else None`.

2020-08-28 08:11 UTC, lunaryorn reviewed
Looks good now, did you test this on your system?

2020-08-28 08:13 UTC, axelgenus commented
> Looks good now, did you test this on your system?

Yes, I am using it right now and it seems to work just fine.

2020-08-28 09:56 UTC, lunaryorn approved these changes

2020-08-28 09:56 UTC, merged

2020-08-28 16:48 UTC, lunaryorn commented
I pushed a new release to gnome extensions, but review my take a while.